homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: -38.161744
  longitude: 144.55609
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Australia/Melbourne
  # Customization file
  customize: !include customize.yaml
  auth_providers:
   - type: homeassistant
   - type: legacy_api_password

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
#   base_url: ha.vicbt.dnsalias.com:8123
  api_password: !secret api_password

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - plex_mediaserver


# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.power_usage
      - sensor.power_export
      - sensor.ceiling_temperature
      - sensor.ceiling_humidity
      
# Enables a map showing the location of tracked devices
map:

zone:
  - name: Home
    latitude: -38.161744
    longitude: 144.55609
    radius: 150
    icon: mdi:home
  - name: Mums
    latitude: -38.192840
    longitude: 144.461258
    radius: 100
    icon: mdi:home-outline
  - name: Kats
    latitude: -38.171471
    longitude: 144.417805
    radius: 100
    icon: mdi:home-outline
  - name: Brians
    latitude: -38.134063
    longitude: 144.327995
    radius: 100
    icon: mdi:home-outline
  - name: Staceys
    latitude: -37.855373
    longitude: 145.267722
    radius: 100
    icon: mdi:home-outline

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
#cloud:

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:3218
#    url: http://vicbt.dnsalias.com:3218

octoprint:
  host: 192.168.1.199
  api_key: 19E8ED52C09340589D5BAA844FC48884
  bed: true
  number_of_tools: 1
  sensors:
    monitored_conditions:
      - 'Current State'

weather:
  - platform: openweathermap
    api_key: 7347768b4a74f8107e5dc9fac948e017    
  
mqtt:
  broker: 192.168.1.90
  discovery: false

  
device_tracker:
  - platform: fritz
  
switch:
  - platform: mqtt
    name: "Timer 1"
    command_topic: "Timer1/toesp"
    payload_on: "{out4:1}"
    payload_off: "{out4:0}"
  - platform: mqtt
    name: "SolarDisplayBlue"
    icon: mdi:led-off
    control: hidden
    command_topic: "Nodemcu1/toesp"
    payload_on: "{out12:1}"
    payload_off: "{out12:0}"
  - platform: mqtt
    name: "SolarDisplayYellow"
    icon: mdi:led-off
    command_topic: "Nodemcu1/toesp"
    payload_on: "{out4:1}"
    payload_off: "{out4:0}"
  - platform: mqtt
    name: "SolarDisplayRed"
    icon: mdi:led-off
    command_topic: "Nodemcu1/toesp"
    payload_on: "{out5:1}"
    payload_off: "{out5:0}"
  - platform: mqtt
    name: Stair Lights
    icon: mdi:lightbulb
    state_topic: stairs/switch/stair_lights/state
    command_topic: stairs/switch/stair_lights/command
    availability_topic: stairs/status    
  - platform: mqtt
    name: Laundry Light
    icon: mdi:lightbulb
    state_topic: skylight/switch/laundry_light/state
    command_topic: skylight/switch/laundry_light/command
    availability_topic: skylight/status    
  - platform: broadlink
    host: 192.168.1.24
    mac: '78:0F:77:5A:E9:87'
    type: rm_mini
    switches:
      moretti_fan:
        friendly_name: "Lounge Fan"
        command_on: JgDUASgQJxAMKygQKA8MLAwrDCwMKwwsKA8MAAEPKBAnEAwrKQ8pDgwsDCsMLAwrDCwoDwwAAQ8oDygQDCsoECgPDCwNKgwsDCsMLCgPDAABDygPKBAMKygQKQ4MLAwrDSsMKw0rKA8MAAEPKQ4oEAwrKBAnEAwsDCsMLA0qDSsnEAwAAQ8oDygQDCsoECgPDCwMKwwsDCsMLCcQDAABDygPKBAMKygQJxAMLAwrDSsNKg0rJxAMAAEPKQ4oEAwrKBAoDwwsDCsMLAwrDCwnEAwAAQ8oDygQDCsoECgPDCwNKgwsDCsMLCcQDAABDykOKQ8MKygQJxAMLA0qDCwMKwwrKBAMAAEPKA8pDwwrKBAnEAwsDSoNKg4qDSooEAwAAQ8oDykPDCsoECcQDCsNKw0qDSsMKygQDAABDycQKBANKigPKBAMKw0rDSoMLAwrKBAMAAEOKBAoDw0rKA8oEA0qDCwMKwwsDSopDwwAAQ4oECkODCwoDygQDCsMLA0qDCwMKykODQABDikPJxAMLCgPKA8NKwwrDSsNKg0rKA8MAAEPKA8oEAwrKBAoDwwsDCsMLAwrDSsoDwwAAQ8oDygQDCsoECgPDCwMKwwsDCsMKygQDAANBQAAAAA==
        command_off: JgCCASgQKA8MLCgPKBAMKwwsDCsMLAwrDCwn8ygQKA8MLCgPKBAMKwwsDCsMLAwrDCwn8ygQKA8MLCgPKA8NKwwrDSsMKw0rDCso8ygQJxANKigQKA8NKwwrDSsMKw0rDCso8ygPKBAMKygQKA8MLAwrDCwOKQ4qDCso8ykOKBAMKygQKA8MLA0qDCwMKwwsDCso8ygPKBAMKygQJxAMKw0rDCsNKwwrDSso8ycQKA8NKygPKBAMKwwsDCsMLAwrDCwo8igQKA8MLCgPKBAMKwwsDCsMLAwrDCwo8igQKA8MLCgPKBAMKwwsDCsMLAwrDCso8ygQJxAMLCcQKA8NKwwrDSsMKw0rDCso8ygQJxAMKygQKA8MLA4pDCwMKwwsDCso8ygPKg4MKygQKA8MLAwrDCwMKw0rDCso8ygPKBAMKygQJxAMKw0rDCsNKwwrDSso8ycQKA8NKygPKBAMKwwsDCsMLAwrDCwo8igQKA8MLCgPKBAMKwwsDCsMLAwrDCsoAA0FAAAAAAAA==
      moretti_fan_swing_lamp:
        friendly_name: "Lounge fan Swing mode (on) Lamp (off)"
        command_on: JgCgASgQJxAMKygQKA8MLAwrKBAMKwwsDCsMAAEPKA8oEAwrKBAoDwwsDCsoEAwrDCwMKwwAAQ8oDygQDCsoECgPDCwMKygQDCsMLAwrDAABDygPKBAMKygQKA8MLAwrKBAMKwwsDCsMAAEPKA8oEAwrKBAnEAwsDCsoEAwrDCwMKwwAAQ8oDygQDCsoECgPDCwMKygQDCsMLAwrDAABDygPKBAMKygQJxAMLAwrKA8NKwwrDSsMAAEPJxAoEAwrKBAnEAwrDSsoDw0rDCsNKwwAAQ8oDygQDCsoECcQDCsNKygPDSsMKwwsDAABDygPKBAMKygQJxAMKw0rKA8MLAwrDCwMAAEPJxAoDw0rKA8oEAwrDCwoDwwsDCsMLAwAAQ4oECgPDCwoDygQDCsMLCcQDCwMKwwsDAABDigQKA8MLCgPKBAMKwwsJxAMKw0rDCsNAAEOKBAnEAwsKA8oDwwsDCsoEAwrDCwMKwwAAQ8oDygQDCsoECgPDCwMKygQDCsMKw0rDAABDycQKBAMKygPKBAMKw0rKA8MLAwrDCwMAA0FAAAAAAAAAAA==
        command_off: JgAiASgPKBANKikPKA8oEA0qDSsMKw0qKQ8o8ygPKBAMKykPJxAoDw0rDCsMLAwrKBAo8ycQKA8NKygPKQ8pDgwsDSoMLAwrKBAo8igQKA8MLCgPKQ8oDw0rDSoMLAwrKBAn8ykPJxANKycQKA8oEAwrDSsNKgwsKA8o8ygPKBAMKykPKA8oEA0qDSsNKg0rJxAo8ycQKBAMKygPKQ8oDw0rDSoMLAwrKBAn8ykPKA8MLCcQKBAnEAwsDCsMKw4qKA8p8ikPJxAMKygQKA8pDwwrDSsNKgwsJxAo8ygPKQ8MKykPKA8oDw0rDSoOKgwrKBAp8SgQKA8NKygPKBAnEAwsDCsMLA0qKA8o8ykPJxAMKygQKA8pDw0qDSsMKw0rKA8pAA0FAAAAAAAA==

input_boolean:
  house_occupied:
    name: "House Occupied"
    initial: on
  steve_home:
    name: "Steve Home"
    initial: off
  maria_home:
    name: "Maria Home"
    initial: off

input_select:
  heater_mode:
    name: Heating Mode
    options: 
      - "Off"
      - "Heat"
      - "Cool"
    initial: "Off"
    icon: mdi:snowflake

notify:
  - platform: kodi
    name: Lounge
    host: 192.168.1.97
    port: 9090
    username: KodiRemote
    password: !secret kodi_password

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml