### Sensors ###
- platform: bom
  station: "IDV60801.94857"
  name: "Geelong"
  monitored_conditions:
    - apparent_t
    - air_temp
    - rel_hum
    - wind_spd_kmh
   
 ### Solar - emonCMS
- platform: mqtt
  name: "Power Solar"
  state_topic: "power/solar"
  unit_of_measurement: "W"
  expire_after: 60
- platform: mqtt
  name: "Power Export"
  state_topic: "power/export"
  unit_of_measurement: "W"
  expire_after: 60
- platform: mqtt
  name: "Power Usage"
  state_topic: "power/usage"
  unit_of_measurement: "W"
  expire_after: 60  
- platform: mqtt
  name: "Voltage"
  state_topic: "power/voltage"
  unit_of_measurement: "V"
  expire_after: 60
- platform: mqtt
  name: "Power Input"
  state_topic: "power/input"
  unit_of_measurement: "W"
  expire_after: 60
- platform: mqtt
  name: "Power Output"
  state_topic: "power/output"
  unit_of_measurement: "W"
  expire_after: 60
- platform: mqtt
  name: "Power Temperature"
  state_topic: "power/temp"
  unit_of_measurement: "°C"
  expire_after: 60


- platform: time_date
  display_options:
    - 'time'  


- platform: scrape
  resource: http://www.bom.gov.au/vic/forecasts/melbourne.shtml
  name: Melbourne Forecast Summary
  select: ".main .forecast p"
  value_template: '{{ value | truncate(255) }}'
  # Request every hour
  scan_interval: 3600
  headers:
    User-Agent: Mozilla/5.0
- platform: scrape
  name: BOM Tweet
  resource: https://twitter.com/BOM_VIC
  select: ".js-tweet-text-container .tweet-text"
  