esphomeyaml:
  name: skylight
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: 'Homeair2'
  password: 'mariaandsteve'
  domain: '.fritz.box'

api:

# Enable logging
logger:

i2c:
  sda: 5
  scl: 4
  scan: False
ota:

# Example configuration entry
sensor:
  - platform: sht3xd
    temperature:
      name: "Laundry Ceiling Temperature"
    humidity:
      name: "Laundry Ceiling Humidity"
    address: 0x45
    update_interval: 15s

switch:
  - platform: gpio
    pin: D6
    name: "Laundry Light"
  - platform: restart
    name: "Laundry Restart"
